### ISSUE TITLE
The game crashes at world gen on MacOS

### ISSUE THREAD

**Issue by cpotemski** [ChosenArchitect/ChosensModdedAdventure#13]
**Describe the bug**
I made a fresh download of the modpack in CurseForge and at creation of the first world the game crashes (before the "tiles screen"). Minecraft launcher just says "Exit code: 6" which seems like a normal "error during runtime"
->

**To Reproduce**
1. boot CurseForge
2. download mudpack
3. launch Minecraft
4. create first world

**Expected behavior**
-> I think that one is obvious

**Crashlog**
[hs_err_pid91980.log](https://github.com/ChosenArchitect/ChosensModdedAdventure/files/12781238/hs_err_pid91980.log)

**Modpack version**
-> 0.1.2 (but also tried 0.1.0 and 0.1.1)
**Java Version**
-> 17.0.8
**Modpack Launcher Used**
-> CurseForge
**Ram Allocated**
-> 16 GB

**Additional context**
-> I am playing on MacOS Sonoma (14.0). Vanilla Minecraft 1.20.2 runs just fine. Also other modpacks play well

**Comment by MalaChaiLatte** [comment]
Change your java to 17.0.6, This issue normally occurs from using java 17.0.7 or later

**Comment by cpotemski** [comment]
That's a good suggestion but definitely not an easy fix as the Minecraft launcher per default uses the default java packaged with the launcher that is at 17.0.8 and homebrew and sdkman both do not offer 17.0.6 anymore as it is too old by now.
I will keep trying to figure out a way I could get such an old version and manually install and change it in the launcher profile, but I think we should find a better solution.

Do you know what the specific problem is?

I already tested Java 20 but that seems not compatible as well :/

PS: Found the version here: https://learn.microsoft.com/en-gb/java/openjdk/older-releases#openjdk-17 (use the one with Architecture AArch64 / M1) and will try it later today

**Comment by cpotemski** [comment]
Okay 17.0.6 was the "solution" but I still think the root cause should be solved. I would love to assist

**Comment by MalaChaiLatte** [comment]
I use an M1 Macbook air to play mc, This issue persists across almost all packs I play, Which is why I just use prism launcher to play as I can download any java version and choose it without much hassle.

Specifically, I use GraalVM or Zulu depending on how I'm feeling

https://www.azul.com/downloads/?version=java-17-lts&os=macos&architecture=arm-64-bit&package=jdk&show-old-builds=true#zulu

**Comment by MalaChaiLatte** [comment]
The original post I used to fix this, https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3325

**Comment by cpotemski** [comment]
Thank you for your help :)

**Comment by cpotemski** [comment]
A quick addition, that makes it even more annoying. Curseforge overrides the launcher_profiles.json on every start of the modpack so I have to configure the correct executable on EVERY start of the game

**Comment by MalaChaiLatte** [comment]
Hence my use of prism launcher
